# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 0.22.0
_src_path: gh:radio-aktywne/template-service-litestar
accountname: radio-aktywne
description: Broadcast scheduling service 📅
docs: true
docsurl: https://radio-aktywne.github.io/mantis
envprefix: MANTIS
imagename: services/mantis
importname: mantis
port: 10800
registry: true
releases: true
reponame: mantis
repourl: https://github.com/radio-aktywne/mantis
servicename: mantis
