# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 0.17.0
_src_path: gh:radio-aktywne/template-service-litestar
accountname: radio-aktywne
description: Broadcast scheduling 📅
docs: true
docsurl: https://radio-aktywne.github.io/emischeduler
email: it@radioaktywne.pl
envprefix: EMISCHEDULER
events: false
imagename: services/emischeduler
importname: emischeduler
port: 33000
registry: true
releases: true
reponame: emischeduler
repourl: https://github.com/radio-aktywne/emischeduler
servicename: emischeduler
