# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 0.17.0
_src_path: gh:radio-aktywne/template-service-litestar
accountname: radio-aktywne
description: Broadcast scheduling 📅
docs: true
docsurl: https://radio-aktywne.github.io/mantis
email: it@radioaktywne.pl
envprefix: MANTIS
events: false
imagename: services/mantis
importname: mantis
port: 10800
registry: true
releases: true
reponame: mantis
repourl: https://github.com/radio-aktywne/mantis
servicename: mantis
